### PR TITLE
Italian documentation

### PR DESCRIPTION
**Pull request by Dil3mm4**

### CODE REVIEW

**Comment by ClockSelect** [comment]
Great!
I do not speak Italian so we'll have to wait for returns from Italian people :)
Translation is a tedious work, that's awesome.

**Comment by ClockSelect** [comment]
Two things, already: links on the main menu are still in english, and links do not work :/

**Comment by Dil3mm4** [comment]
> Two things, already: links on the main menu are still in english, and links do not work :/

Fixed in the new pull request.

> Translation is a tedious work, that's awesome.

It really is. 
But I believe in free knowledge for all. 
It's a mess to have language barriers, so if I can help people to understand things in their own language or to improve something, why not. 
Still, the project deserves it.

**Comment by enricorov** [comment]
Italian here, looks good at first sight.

**Pull request merged**
