### PR TITLE
Update battery.c

### PR DESCRIPTION
**Pull request by Ponczek87**
This is my proposition for 1% battery showing.

### CODE REVIEW

**Comment by ClockSelect** [comment]
Well, it's exactly the way it should _not_ be done.
Discharge curves are highly non-linear and you can't interpolate in the full range. If you use this method, it'll tell you between 20~30% when you actually have 10% or less.
And 4.21 is almost overcharged; you can't base your 100% on it. Let your battery stay still one day and check it; it'll still be 100% charged, but will have dropped to about 4.1V.

**Comment by Ponczek87** [comment]
How can I compile this with your firmware changes and test to check how it'll work? :D

**Comment by ClockSelect** [comment]
Everything should be in the readme file follow the instructions and tell me if you have problems.

**Comment by ClockSelect** [comment]
What about the last releases?
Does it fit your needs?

**Pull request closed without merging**
