### PR TITLE
Bypass realtime power setting

### PR DESCRIPTION
**Pull request by malinges**
When using bypass mode, I often find myself grabbing a calculator to compute the actual power output.
The power value displayed at idle (not firing) is indeed fairly inaccurate, because of battery voltage sag, and in my case, varying resistance of my SS coils.
And while firing, the power display is replaced with the voltage output.

So here it is: a small patch to allow displaying realtime power in bypass mode, with the accompanying setting in the Interface menu.
The code is very straightforward, but you should note I only tested it on my VTC Mini.

And by the way, thanks for your great work!

### CODE REVIEW

**Comment by ClockSelect** [comment]
Since output voltage is available on the third line, we could as well replace the top voltage by the power. I the configuration option really needed? Voltage is not really a pertinent vaping information, anyway.

**Comment by malinges** [comment]
I totally agree, output voltage is already available on the third line, so a setting seems unnecessary.
Simply displaying output power as the main info looks like the best way to go. Power is not available anywhere else in bypass mode, and is certainly more relevant than voltage for most people.
I didn't think about that, and decided to go with a "default off" setting as you seem to favor stock experience whenever possible. But eh... less code is (almost) always better ;-)

**Comment by ClockSelect** [comment]
You may give it a try.
I've redone the power/volts computation estimates before firing so they're a bit more realistic.

**Comment by malinges** [comment]
Ok sorry for closing the issue, I didn't know reverting changes on my repo would close the pull request.
I just tested your last version, it works very well.
Taking battery internal resistance into account is a very good idea!
I think it would have given me a very accurate power estimation... if it wasn't for that damn SS coil! I think I'll give a good old Kanthal coil a try, just for fun.
Thanks for this change, this is even better than what I would have done!

**Comment by ClockSelect** [comment]
Coils with high TCR will always be inacurate, obviously, since their resistance is inpredictable (unless we know everything about the coil: gauge, mass, etc). But it should reasonabily work with Kanthal.

**Pull request closed without merging**
