### PR TITLE
Fix Logo Screen Saver

### PR DESCRIPTION
**Pull request by Daveee10**
Screen saver showed black screen when logo was switched off

### CODE REVIEW

**Comment by ClockSelect** [comment]
I'm perfectly ok with this "bug".
Maybe we could reconsider it if we make a full-screen logo functionality.

**Comment by Daveee10** [comment]
Maybe. But imo with this bug the logo option in ssaver is useless. I'm not using logo on main screen but on screen saver. Now that's for another users not an option because without mainscreen logo don't work the screen saver too.

**Comment by Daveee10** [comment]
In other hand what do you mean full screen logo functionality?

**Comment by ClockSelect** [comment]
I made it on my side - avoiding merging with confilcts.

**Pull request closed without merging**
